### ISSUE TITLE
Fix vanilla formation selection saving

### ISSUE THREAD

**Issue by tbeswick96** [tbeswick96/BannerlordYetAnotherPartyOrganiser#11]
# Description

- Vanilla saving of formation choices for units is broken
- Permission has been granted to utilise logic from this mod https://www.nexusmods.com/mountandblade2bannerlord/mods/626

# Context

- Within scope of this mod to fix it
- Improves UX of party management

**Comment by MLNW** [comment]
I was looking through the referenced mod description but couldn't find a link to their repository. Do you have a link @tbeswick96 ?

**Comment by tbeswick96** [comment]
Ah the author said to decompile the dll as reference for our implementation

**Comment by tbeswick96** [comment]
Going to assign you to this @MLNW

**Comment by MLNW** [comment]
It's implemented and works find for 1.1.1. Since switching beta branches is a pain it was only validated once on the 1.2.0 branch.

Since it modifies the save game I'm not 100% confident to merge it without another person validating the fix. Once that is done we can merge the feature.

**Comment by tbeswick96** [comment]
Tested beta 1.2.0, working fine
