### ISSUE TITLE
Game unable to start with mod loaded. Saves unable to be loaded with savegames that where using it.

### ISSUE THREAD

**Issue by NicTanghe** [tbeswick96/BannerlordYetAnotherPartyOrganiser#17]
# Description

# Expected Behaviour

# Actual Behaviour

# Steps to Reproduce

- Step 1
- Step 2
- Step 3

# Additional context

# Screenshots

**Comment by MLNW** [comment]
Please fill out the issue template

**Comment by MLNW** [comment]
@NicTanghe please provide us with more information or we cannot help with this issue

**Comment by MLNW** [comment]
Try using [Save Missing Module Fix](https://www.nexusmods.com/mountandblade2bannerlord/mods/282) as described in the README.

Since there is no interaction from the user and generally no information given I will close the issue.

**Comment by NicTanghe** [comment]
save missing modules fix did not fix the issue. switched to using
otherparty organiser.

Op di 21 apr. 2020 om 12:24 schreef MLNW <notifications@github.com>:

**Comment by MLNW** [comment]
@NicTanghe please send us the affected save game so we can investigate
