### ISSUE TITLE
Troops Upgrade is ignoring the Disciplinarian perk rules

### ISSUE THREAD

**Issue by SerjTargarien** [tbeswick96/BannerlordYetAnotherPartyOrganiser#18]
The "Upgrade all" button can upgrade bandits into normal troops without the disciplinarian perk. It should do a check before doing so and ignore those troops if you don't have it.

Additionally, this is not a bug report but a suggestion. When upgrade rules are finally implemented, "don't upgrade bandits" should be implemented as a rule for role-playing purposes.

**Comment by MLNW** [comment]
Duplicate of #5, sounds like it wasn't fixed after all @tbeswick96

**Comment by MLNW** [comment]
Closing in favor of old issue
