### ISSUE TITLE
Update Harmony to 2.0.0.9

### ISSUE THREAD

**Issue by MLNW** [tbeswick96/BannerlordYetAnotherPartyOrganiser#19]
We downgraded our used Harmony version to 2.0.0.0 because UIExtender was using that version. They will be upgrading with the next release and there is no reason for us to use their version either: https://github.com/shdwp/UIExtenderLib/issues/7

# Description
Upgrade Harmony from 2.0.0.0 to 2.0.0.9

**Comment by tbeswick96** [comment]
Closed with https://github.com/tbeswick96/BannerlordYetAnotherPartyOrganiser/pull/25
