### ISSUE TITLE
Improve exception handling and reporting

### ISSUE THREAD

**Issue by MLNW** [tbeswick96/BannerlordYetAnotherPartyOrganiser#3]
The default system of reporting exceptions for mods isn't very verbose. It makes it hard to figure out what is wrong when users report issues. I haven't found a perfect solution yet but there are other modders that at least display the full stack trace when something goes wrong.

One example would be from BannerlordTweaks: https://github.com/mipen/BannerlordTweaks/blob/master/SubModule.cs:
```
protected override void OnSubModuleLoad()
{
    base.OnSubModuleLoad();
    try
    {
        FileDatabase.Initialise(ModuleFolderName);
        SettingsDatabase.RegisterSettings(Settings.Instance, Settings.Instance.ModName);

        var harmony = new Harmony("mod.bannerlord.mipen");
        harmony.PatchAll();
    }
    catch (Exception ex)
    {
        MessageBox.Show($"Error Initialising Bannerlord Tweaks:\n\n{ex.ToStringFull()}");
    }
}
```

They use a simple `MessageBox` from `Windows.Forms` to display the full stack trace of exceptions.

I just saw that for implementing this they use [ModLib](https://github.com/mipen/ModLib/blob/master/ExtensionMethods/ExceptionExtensionMethods.cs) which may also be used for an in-game settings view that is utilized by BannerlordTweaks for some quite extensive settings.

We should maybe think about using this ModLib for both of these tasks or find another way to make debugging user errors more verbose.

**Comment by MLNW** [comment]
Now that we have added ModLib and use it for debugging purposes `OnSubModuleLoad` I'm not exactly sure where else we need to improve exception handling.

ModLib already patches the finalizer of the `OnApplicationTick` method to look for exceptions and show them to the user. I simply haven't been able to try this feature out since adding ModLib.

**Comment by tbeswick96** [comment]
Sounds good, but I think some more generic error handling within the mod code itself would be prudent. SOme strategically placed trys on various actions so as not to cause CTDs where possible

**Comment by MLNW** [comment]
The mod now uses ModLib to report exceptions on start up. If there are other critical places that need additional exception handling we should do that while implementing other changes.

The initial mission of this issue has been completed. Closing.
