### ISSUE TITLE
Recruiting prisoners does not update prisoner list correctly

### ISSUE THREAD

**Issue by Helomi** [tbeswick96/BannerlordYetAnotherPartyOrganiser#32]
Click recruit all prisoners
Add right ammout of troops to your army but removes only 1 troop from prisoners

Version 1.1.2

30 sec video explaining bug
https://youtu.be/yxg06kWLcRM

**Comment by MLNW** [comment]
@Urky is this something that will be fixed by #28 ?

**Comment by tbeswick96** [comment]
Should be fixed
