### ISSUE TITLE
Crash on load with latest release 1.2.0

### ISSUE THREAD

**Issue by teranian** [tbeswick96/BannerlordYetAnotherPartyOrganiser#37]
I have tried both the BETA and non-beta files. With the Beta file i get a non-descript crash, with the NON BETA file i get the error in the attached screenshot. 

# Description
I get a crash on load with the following error: 
![image](https://user-images.githubusercontent.com/12546984/80293646-475ec180-87a4-11ea-9b22-3a77846f2daa.png)

UI extender lib has been removed entirely from the mod list.

**Comment by tbeswick96** [comment]
Could please post your mod load order? The game will load the first harmony dll it finds, even if it is an older version.
To ensure a usable version is loaded, please try placing ModLib as the first community mod in your loader order after the official mods, and let me know if that works

**Comment by teranian** [comment]
Sure can. I've put ModLib straight after the official modules. 
I've tried BYAPO directly after ModLib and also right down the bottom and had the same error both times. 

![image](https://user-images.githubusercontent.com/12546984/80297915-01692400-87cb-11ea-9ee1-446cede12c71.png)

**Comment by teranian** [comment]
I get the same error when loading only ModLib and YAPO.

If i hit OK on the error the game loads to the main menu. 
I can't load old saves and the party screen doesn't show the mod UI for new campaigns either. 

Load Order: 
![image](https://user-images.githubusercontent.com/12546984/80298452-d8975d80-87cf-11ea-89a4-a86664ebac6b.png)

Error: 
![image](https://user-images.githubusercontent.com/12546984/80298459-f06ee180-87cf-11ea-9925-b4aae9e0bd3f.png)

**Comment by MLNW** [comment]
The mod load order of the official modules looks a little weird. Just to make sure that isn't the culprit try it with this order:

- Native
- SandBoxCore
- SandBox
- StoryMode
- CustomBattle

**Comment by teranian** [comment]
No change with the core mods in the order you've asked. Same error. 

![image](https://user-images.githubusercontent.com/12546984/80303242-4fdde900-87f2-11ea-9692-afbdcdaba31f.png)
![image](https://user-images.githubusercontent.com/12546984/80303258-63894f80-87f2-11ea-84cd-1b66d05e8fd3.png)

**Comment by tbeswick96** [comment]
Hi,

Sorry that you're having issues, can you try something for me? This crash usually means an old version of harmony is being loaded by the game somewhere, and if not by a mod, it could be elsewhere.

Could you try the following:
- Go to bannerlord install directory
- Search for 0harmony.dll
- Once search complete, change to details view
- Right click the column headers, click More, and select `File Version` in the list

This will show you the versions of harmony in your install location. Check to see if any are 2.0.0.8 or less, and note their paths.
If the launcher you use uses symlinks, you'll need to do this in the same location where it stores the mods.

Once you've got all that info, if you could past a screenshot or two of the paths here, or if something looks out of place then that could be the issue. For example if this launcher uses harmony at all it could be loading an old version itself.

If that doesn't get us anywhere, then we'll have to do more tests on our end as well.

I will note launching the game on beta branch with only the vanilla modules, modlib, save party fix, and yapo installed via the fixed launcher works for us. I will try with this launcher too and see if it produces different results

**Comment by tbeswick96** [comment]
I've just tried with the launcher you're using, and the game launches fine. I think there must be some stray version of harmony being loaded somewhere in your setup

**Comment by MLNW** [comment]
It may very well be that one of the installed mods that aren't loaded have an old version of harmony and for some reason that version is loaded.

I've heard of something similar before.

**Comment by teranian** [comment]
Hrm. Vortex uses Symlinks by default and explorer won't show file versions:

![image](https://user-images.githubusercontent.com/12546984/80304748-69cff980-87fb-11ea-9ac9-35b870f1102f.png)

But switching to Hardlinks shows two mods using 2.0.0.8. 

![image](https://user-images.githubusercontent.com/12546984/80304814-df3bca00-87fb-11ea-9851-717d629ff7ff.png)

**Comment by teranian** [comment]
If i get rid of all the other mods and just load ModLib and YAPO 

![image](https://user-images.githubusercontent.com/12546984/80304911-ad773300-87fc-11ea-80b4-e1a9d0ec2e21.png)

I still get the error:
![image](https://user-images.githubusercontent.com/12546984/80304923-bf58d600-87fc-11ea-99a2-a07b2c1726e6.png)

And 0Harmony.dll's are showing no 2.0.0.8 versions
![image](https://user-images.githubusercontent.com/12546984/80304928-d0094c00-87fc-11ea-9f0a-d1381cd05b88.png)

**Comment by teranian** [comment]
Using the Vanilla launcher with only ModLib and YAPO also results in the error: 
![image](https://user-images.githubusercontent.com/12546984/80305006-60e02780-87fd-11ea-9f4a-55bbbce1fd9b.png)

**Comment by tbeswick96** [comment]
Ok, thanks for doing that, I may have to try building a custom version of UIExtenderLib that can use older versions of Harmony.

**Comment by teranian** [comment]
Let me know if i can send any other info. 

Thanks for making such a great mod!

**Comment by tbeswick96** [comment]
Fixed in https://github.com/tbeswick96/BannerlordYetAnotherPartyOrganiser/releases/tag/1.2.1
