### ISSUE TITLE
Crash's while launching/

### ISSUE THREAD

**Issue by Filipp-Ov** [tbeswick96/BannerlordYetAnotherPartyOrganiser#40]
# Description
I updated game to last stable 1.3.1 and updated all mods, include this. And now all saves don't load without this mod and game crash's when mod is on and I try to launch game.

# Screenshots

![image](https://user-images.githubusercontent.com/64666994/81447904-22942200-9186-11ea-9247-e625c05e9fdf.png)

**Comment by tbeswick96** [comment]
Hi, I've not looked at the update yet so will need to release a patch for the latest release.
In the meantime, you should be able to load your saves with this mod disabled, if you add and enable https://github.com/bmountney/Aragas.AltSaveSystemFix/releases/tag/1.3.0.0 I've tested this with my mod and it does work

**Comment by Filipp-Ov** [comment]
Hmm, game launched but I can't load any saves. When I click on "Load" button in save menu sometimes nothing happened and sometimes game crashes with this message. 
![image](https://user-images.githubusercontent.com/64666994/81452764-60964380-9190-11ea-9a53-58f7c3067be0.png)
Maybe you know what it could be?

**Comment by MLNW** [comment]
Hey @Filipp-Ov, a new version was released that should fix the issue. Best try it out and let us know how it goes.

**Comment by Filipp-Ov** [comment]
Thank you @MLNW! I'll try it today :)

**Comment by Filipp-Ov** [comment]
Unfortunately, now game crashes, while any saves loading, without messages.
I think it'll be related to another mod. I'm checking it.

**Comment by tbeswick96** [comment]
Make sure you've updated modlib

**Comment by Filipp-Ov** [comment]
All mods updated, but when I launch game with ModLib, Aragas.AltSaveMissingModuleFix and YAPO game crashes :(

![image](https://user-images.githubusercontent.com/64666994/81706427-af85f680-9478-11ea-8ec4-4271c75be428.png)

**Comment by tbeswick96** [comment]
Can you confirm which game branch you're on in the steam `properties > betas` tab for MBB?
This error occurred due to this mod referencing things from the older builds of the game
Also please confirm your modlib version for me

**Comment by Filipp-Ov** [comment]
I reloaded all mods and now this problem is gone.
But "When I click on "Load" button in save menu nothing happened."
Game version = e1.3.0
ModLib = 1.3.4

**Comment by tbeswick96** [comment]
I think 1.3.0 is an older beta version and might not work anymore, can you try setting the beta selection either the one that ens with beta or opt out? Correct me if I'm wrong.

Also if nothing happens on load, try loading with the alternative save fix before this mod

**Comment by Filipp-Ov** [comment]
I installed the latest not beta version e1.3.1 and it's the same like opt out.

Alternative save fix already installed and ahead of YAPO.

Problem on the same place.

**Comment by tbeswick96** [comment]
So the game loads fine now but you have issues loading a save? The save might be corrupt and not recoverable...TaleWorlds handle loading of saves really badly so it's a very fragile system. If the alternative save fix isn't working then I'm not sure what else to suggest. You could try loading only Modlib, the Save fix, and YAPO, and see what happens when you try to load that save

**Comment by Filipp-Ov** [comment]
Unfortunately, I think that's it happened(
Any combinations of mods doesn't help, but I still can load old saves without mods, that's not so bad)
Thank you for your help and good luck!

**Comment by tbeswick96** [comment]
Ok, if you want to upload that latest save here and your mod list, I can attach a debugger and find out where it's failing. If it's something trivial, then I can possibly notify the save fix guys so they can add it to their solution

**Comment by Filipp-Ov** [comment]
![1](https://user-images.githubusercontent.com/64666994/81840068-1e368300-9551-11ea-85bf-f2bc88060e47.JPG)
![2](https://user-images.githubusercontent.com/64666994/81840072-1ecf1980-9551-11ea-9770-378e4a3ad021.JPG)
![3](https://user-images.githubusercontent.com/64666994/81840074-1f67b000-9551-11ea-885a-abd9937f307b.JPG)
https://drive.google.com/open?id=1upp4EeHrc5D3GQ_i9tXxxeKYUQD6hMRX

That's old save with mod list.

**Comment by Filipp-Ov** [comment]
![4](https://user-images.githubusercontent.com/64666994/81840540-d6642b80-9551-11ea-932e-62e38c94ab15.JPG)
![5](https://user-images.githubusercontent.com/64666994/81840543-d7955880-9551-11ea-96f7-9b1e25934930.JPG)
![6](https://user-images.githubusercontent.com/64666994/81840546-d7955880-9551-11ea-851d-c7bf161e8a3c.JPG)
https://drive.google.com/open?id=1A1wXi2djoweRibELCrZ5YK9IzQ_fuNtf

And that's another save which I started after same problem on a newer one version of the game.

**Comment by tbeswick96** [comment]
@Filipp-Ov I am able to load the second save with that mod list (minus the russian mods).
I've not tried the first save

I recommend double checking you're opted out of any old game versions and do a steam game files verify, then check all the mods you have loaded are up to date (making sure to use specific stable/beta versions) then see if you can load the save.
If not, I can load the save and save it again to see if that fixes it and then upload it for you

**Comment by Filipp-Ov** [comment]
I'll be grateful if you'll can load the first save game and it'll work.

**Comment by tbeswick96** [comment]
@Filipp-Ov Hey, I've put this down to `Fixed Formations` breaking the first save. I can load the save with that enabled (with some YAPO stuff commented out as it does the same thing), but if I load it with it disabled it won't load the save, even with the save fixer

**Comment by Filipp-Ov** [comment]
@tbeswick96 Yeah, I thought about this mod too(
Can You explain what to do, to load the this save with enabled 'Fixed Formations'?

**Comment by tbeswick96** [comment]
Not heard anything since, and formation saving is handled by the game itself now, closing this
