### ISSUE TITLE
Party Screen Buttons Stopped Working

### ISSUE THREAD

**Issue by MrGalo1992** [tbeswick96/BannerlordYetAnotherPartyOrganiser#42]
# Description
I updated to 1.4.2 Beta on my current campaign and the three "Cancel", "Done", "Reset" and the transfer all (Prisoner, Soldiers) buttons stopped working. I tested it for about and hour and its pretty likely this mod causes the issue as removing it and starting a new campaign solves the issue.

When I enter Party Screen the log shows two messages: "Refresh View" and "First Refresh". I don't know exactly what that means, and how I could refresh but I noticed it in 1.4.1 too and experienced no problem.

# Expected Behaviour
Working menu buttons.

# Actual Behaviour
When I click the buttons I can hear the usual sound, the icons are flashing normally but clicking on them do nothing.

# Steps to Reproduce
- Step 1: simply opening the Party Screen and clicking buttons, or fight a battle and there the Party Screen tab has this issue too so sadly I can not take prisoners right now at all (I need to hit Esc to proceed) and "Transfer All Troops/Prisoners" buttons stopped working as well.

# Additional context
I tried to remove the mod with and without the ALTERNATIVE Save Missing Module Fix but either way when I click "Load" it does not function similar to the 3 buttons mentioned above so I cannot load the save without the mod. I tried a new campaign, the issue is the same. I did a clean reinstall - with config files removed too - the issue is the same. I opened the source code in VS too and rebuilded it with the 1.4.2 DLL-s but the issue is the same, I'm suspecting the mod needs a ModLib update, but I just started to dive into codes so it's just a guess.

**Comment by tbeswick96** [comment]
Should be fixed
