### ISSUE TITLE
Upgrade prisoners does not respect disciplinarian perk

### ISSUE THREAD

**Issue by MLNW** [tbeswick96/BannerlordYetAnotherPartyOrganiser#5]
If you have bandit troops with you that only have one upgrade path, e.g. forest bandit, you are able to upgrade them even without having the disciplinarian perk.

This should be taken into consideration when upgrading.

**Comment by tbeswick96** [comment]
Can I leave this with you to fix?

**Comment by HaydenReeve** [comment]
If I may add to this, the button also does not respect horse/warhorse requirements.

**Comment by MLNW** [comment]
@Greysion Thank you for your comment. This is all going to be taken into account with #28

**Comment by tbeswick96** [comment]
Closed by #28
