### ISSUE TITLE
Reliably crashes on ctrl+click on recruit all button

### ISSUE THREAD

**Issue by Fumblesneeze** [tbeswick96/BannerlordYetAnotherPartyOrganiser#8]
Reliably crashes on ctrl+click on recruit all button

# Expected Behaviour
not to crash

# Actual Behaviour
crashes

# Steps to Reproduce

Reliably crashes on ctrl+click on recruit all button

# Additional context
1.1.0 stable game, bunch of other mods installed

> 
> Recorded Unhandled Exceptions:
>   1. System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
>        at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
>        at TaleWorlds.Library.Common.GetStackTraceRaw(Exception e, Int32 skipCount)
>        at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
>        at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
>        at TaleWorlds.Library.Common.PrintDynamicInvokeDebugInfo(Exception e, MethodInfo methodInfo, Object obj, Object[] args)
>        at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
>        at DMD<DMD<ExecuteCommand_Patch1>?33362883::ExecuteCommand_Patch1>(ViewModel this, String commandName, Object[] parameters)
>        at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand(String command, Object[] args)
>        at TaleWorlds.GauntletUI.Widget.EventFired(String eventName, Object[] args)
>        at TaleWorlds.GauntletUI.ButtonWidget.HandleClick()
>        at TaleWorlds.GauntletUI.ButtonWidget.OnMouseReleased()
>        at TaleWorlds.GauntletUI.EventManager.MouseUp()
>        at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
>        at TaleWorlds.Engine.Screens.ScreenManager.Update()
>        at TaleWorlds.Engine.Screens.ScreenManager.Tick(Single dt)
>        at DMD<DMD<ScreenManager_Tick_Patch1>?42783083::ScreenManager_Tick_Patch1>(Single dt)

**Comment by tbeswick96** [comment]
Fixed in 1.1.2
